### ISSUE TITLE
Release-flow not including generated texture file on MacOS

### ISSUE THREAD

**Issue by bbarker** [bbarker/voxel-vegetables#28]
The file in question is:

```
assets/textures/tile_textures.png
```

It seems to be included in other platforms.

The excerpt looks correct to me in `release.yaml`:

```yaml
      - name: Create Universal Binary
        run: |
          # lipo -create -output target/release/${{ env.GAME_EXECUTABLE_NAME }} target/aarch64-apple-darwin/release/${{ env.GAME_EXECUTABLE_NAME }} target/x86_64-apple-darwin/release/${{ env.GAME_EXECUTABLE_NAME }}
          lipo -create -output target/debug/${{ env.GAME_EXECUTABLE_NAME }} target/aarch64-apple-darwin/debug/${{ env.GAME_EXECUTABLE_NAME }} target/x86_64-apple-darwin/debug/${{ env.GAME_EXECUTABLE_NAME }}
      - name: Create release
        run: |
          mkdir -p build/macos/src/Game.app/Contents/MacOS/assets
          cp -r assets/ build/macos/src/Game.app/Contents/MacOS/assets
          cp -r credits/ build/macos/src/Game.app/Contents/MacOS/credits
```
